### ISSUE TITLE
how to install on localhost and any live demo

### ISSUE THREAD

**Issue by Arman143** [apal21/PHP-Laravel-5.4-custom-blog-CMS#1]
hi,
      i like your work, i ty to install it on localhost but i can't find database files.. sql script.. or any installer .. can you provide demo link and detailed installation process.

Regards
Arman

**Comment by apal21** [comment]
Can you tell me what did you do exactly while installing this? Tables will be installed automatically after executing "php artisan migrate". But first you have to create a database. If you haven't changed anything in .env file then you have to create a database named "laravel".

**Comment by Arman143** [comment]
i have install it. but its in dev stage ...

F:\wamp64\www\laravel>php artisan migrate
Migration table created successfully.
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2017_01_28_100105_create_posts_table
Migrated: 2017_01_31_134956_add_slug_to_posts
Migrated: 2017_02_02_110731_create_categories_table
Migrated: 2017_02_02_111217_add_category_id_to_table
Migrated: 2017_02_04_105943_create_tags_table
Migrated: 2017_02_04_111141_create_post_tag_table
Migrated: 2017_02_05_140611_create_comments_table
Migrated: 2017_02_11_112459_add_image_col_to_posts

F:\wamp64\www\laravel>

Thanks

**Comment by apal21** [comment]
Yes I'll update some security features in future. Still you can use all the features. Add /register after URL to create new account and /login to log into it and delete/update/create all posts.

**Comment by Arman143** [comment]
great work but the design is need more improvement,,, try to crate it like https://goo.gl/JYnlXR just the designs and functionality...
 
your blog is also great .... but there is no sidebar when you open signal post.

**Comment by apal21** [comment]
I know, I didn't designed it and probably won't design this. I've left this portion untouched because users can create their own stylesheet according to their requirement.

You can tell here what you want in the single post sidebar. I'll do it in 1-2 days.

**Comment by Arman143** [comment]
i think sidebar will be ok.. for displaying ads and recent post, tags etc..
also add new section under admin Ad Management and place ads in better location.. for high ctr.. if someone use the blog of adsense like me..

**Comment by apal21** [comment]
Ok so I will add a blank sidebar. Thanks for the suggestions.
If you want to do this manually then just add a div below the post and above the comments section

**Comment by apal21** [comment]
If you want to do this manually then just add a div below the post and above the comments section
