### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by yuri25** [apal21/PHP-Laravel-5.4-custom-blog-CMS#2]
How to log in the admin? Is there an admin panel? How to publish blogs and posts?
Nice system!

**Comment by apal21** [comment]
Yes you can log in via adding /login to the url.
For example if your site is example.com then just go to example.com/login

In localhost:8000, type localhost:8000/login

**Comment by apal21** [comment]
You can also create a new user by adding /register

**Comment by yuri25** [comment]
Thank you very much, registered users admin and it worked. Continue development please.

**Comment by apal21** [comment]
Yeah sure.
